name: quantz
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: 1.14.0
  firebase_messaging: 11.2.12
  google_sign_in: 5.2.4
  google_mobile_ads: 1.2.0
  in_app_purchase: 3.0.2

  momentum: 2.2.1
  shared_preferences: 2.0.13
  fluttertoast: 8.0.9
  flutter_fgbg: 0.2.0
  flutter_local_notifications: 9.4.0
  dio: 4.0.6
  timeago: 3.2.2
  url_launcher: 6.0.20
  jwt_decoder: 2.0.1
  cached_network_image: 3.2.0
  uni_links: 0.5.1
  random_string: 2.3.1
  equatable: 2.0.3
  pull_to_refresh: 2.0.0
  package_info_plus: 1.4.2
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.2

dependency_overrides:
  platform: ^3.1.0

flutter:

  uses-material-design: true

  assets:
    - 'assets/'
    - 'assets/sources-icons/'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
